# Generated by Django 5.0.2 on 2024-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aut', '0002_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
